language: python

matrix:
  include:
    - python: 2.7
      env: PENDULUM_EXTENSIONS=1
    - python: 2.7
      env: PENDULUM_EXTENSIONS=0
    - python: 3.2
      env: PENDULUM_EXTENSIONS=1
    - python: 3.2
      env: PENDULUM_EXTENSIONS=0
    - python: 3.3
      env: PENDULUM_EXTENSIONS=1
    - python: 3.3
      env: PENDULUM_EXTENSIONS=0
    - python: 3.4
      env: PENDULUM_EXTENSIONS=1
    - python: 3.4
      env: PENDULUM_EXTENSIONS=0
    - python: 3.5
      env: PENDULUM_EXTENSIONS=1
    - python: 3.5
      env: PENDULUM_EXTENSIONS=0
    - python: 3.6
      env: PENDULUM_EXTENSIONS=1
    - python: 3.6
      env: PENDULUM_EXTENSIONS=0
    - python: pypy

before_install:
  - pip install codecov

install:
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          pushd "$PYENV_ROOT" && git pull && popd
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="5.6.0"
        "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
      fi
  - pip install -r tests-requirements.txt
  - python setup.py develop

script: py.test --cov=pendulum --cov-config=.coveragerc tests/

after_success:
  - codecov
